<a href="https://colab.research.google.com/github/debashishdas40/Data-Analysis-With-Python-and-Pandas/blob/main/Data_Analysis_With_Python_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy array

In [ ]:
Sales= [0,5,155,0,518,0,1827,616,317,325]

In [ ]:
import numpy as np
sales_array = np.array(Sales)

In [ ]:
type(sales_array)

numpy.ndarray

In [ ]:
print(f"ndim:{sales_array.ndim}")
print(f"shape:{sales_array.shape}")
print(f"size:{sales_array.size}")
print(f"dtype:{sales_array.dtype}")

ndim:1
shape:(10,)
size:10
dtype:int64


In [ ]:
Sales_1= [[0,5,155,518],[1827,616,317,325]]

In [ ]:
sales_array_1=np.array(Sales_1)

In [ ]:
sales_array_1

array([[   0,    5,  155,  518],
       [1827,  616,  317,  325]])

In [ ]:
print(f"ndim:{sales_array_1.ndim}")
print(f"shape:{sales_array_1.shape}")
print(f"size:{sales_array_1.size}")
print(f"dtype:{sales_array_1.dtype}")

ndim:2
shape:(2, 4)
size:8
dtype:int64


In [ ]:
array= np.array(range(5))

In [ ]:
array

array([0, 1, 2, 3, 4])

In [ ]:
array_2d= np.array([range(5),range(5)])

In [ ]:
array_2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])